# Generated by Django 3.0.7 on 2020-06-13 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('respostas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('aprovado', models.BooleanField(default=False)),
                ('resposta', models.ManyToManyField(to='respostas.Resposta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Professor')),
            ],
        ),
    ]
