# Generated by Django 3.0.7 on 2020-06-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='descricao',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta1',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta2',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta4',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta5',
            field=models.TextField(default='NA'),
        ),
    ]
