# Generated by Django 3.0.7 on 2020-06-14 22:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='nome_prova',
            field=models.TextField(default='NA'),
        ),
        migrations.RemoveField(
            model_name='prova',
            name='questoes',
        ),
        migrations.AddField(
            model_name='prova',
            name='questoes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='NA', max_length=49),
        ),
    ]
