# Generated by Django 3.0.7 on 2020-06-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_auto_20200614_1912'),
        ('provas', '0002_auto_20200614_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='questoes',
        ),
        migrations.AddField(
            model_name='prova',
            name='questoes',
            field=models.ManyToManyField(to='questoes.Questao'),
        ),
    ]
